server:
  port: 8080
  tomcat:
    basedir: /tmp/tomcat
  servlet:
    context-path: /io-json

spring:
  application:
    name: jsonread-api
  profiles:
    active: dev1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: messages/messages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@//192.168.1.111:1521/ora11g
    username: demo
    password: demo
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    logSlowSql: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
